---
title: "Extra figures"
author: "Ha Tran"
date: "2024-01-12"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  eval = TRUE,
  fig.align = "center"
)
```


```{r load libraries}
# working with data
library(dplyr)
library(magrittr)
library(readr)
library(tibble)
library(reshape2)
library(tidyverse)

# Visualisation:
library(kableExtra)
library(ggplot2)
library(grid)
library(DT)
library(extrafont)
library(VennDiagram)

# Custom ggplot
library(gridExtra)
library(ggbiplot)
library(ggrepel)
library(rrvgo)
library(d3treeR)
library(plotly)
library(GOSemSim)
library(data.table)

# Bioconductor packages:
library(edgeR)
library(limma)
library(Glimma)
library(clusterProfiler)
library(org.Mm.eg.db)
library(enrichplot)
library(patchwork)

library(pandoc)
library(knitr)
opts_knit$set(progress = FALSE, verbose = FALSE)
opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE)

```

```{r importData}
# load DGElist previously created in the set up
dge <- readRDS(here::here("0_data/rds_objects/dge.rds"))
# lm <- readRDS(here::here("0_data/rds_objects/lm.rds"))
lm_all <- readRDS(here::here("0_data/rds_objects/lm_all.rds"))
lm_sig <- readRDS(here::here("0_data/rds_objects/lm_sig.rds"))
Comp <- readRDS(here::here("0_data/rds_objects/comp.rds"))
Ont <- c("BP","MF","CC")
# to increase the knitting speed. change to T to save all plots
savePlots <- F
export <- F
```

```{r importFunctions}
# Theme
bossTheme <- readRDS(here::here("0_data/functions/bossTheme.rds"))
bossTheme_bar <- readRDS(here::here("0_data/functions/bossTheme_bar.rds"))
groupColour <- readRDS(here::here("0_data/functions/groupColour.rds"))
groupColour_dark <- readRDS(here::here("0_data/functions/groupColour_dark.rds"))
expressionCol <- readRDS(here::here("0_data/functions/expressionCol.rds"))
expressionCol_dark <- readRDS(here::here("0_data/functions/expressionCol_dark.rds"))
compColour <- readRDS(here::here("0_data/functions/compColour.rds"))

DT <- readRDS(here::here("0_data/functions/DT.rds"))

# Plotting
convert_to_superscript <- readRDS(here::here("0_data/functions/convert_to_superscript.rds"))
exponent <- readRDS(here::here("0_data/functions/exponent.rds"))
format_y_axis <- readRDS(here::here("0_data/functions/format_y_axis.rds"))

firstCap <- function(x) {
  substr(x, 1, 1) <- toupper(substr(x, 1, 1))
  x
}

```

## Extra Figures

```{r functionalHeat}
enrichGO_sig <-  readRDS(here::here("0_data/rds_objects/enrichGO_sig.rds"))
enrichKEGG_sig <-  readRDS(here::here("0_data/rds_objects/enrichKEGG_sig.rds"))
reactome_sig <-  readRDS(here::here("0_data/rds_objects/reactome_sig.rds"))
ipaPathway_sig <- readRDS(here::here("0_data/rds_objects/ipa_pathways.rds"))

go <- lapply(enrichGO_sig, function(x) {x %>% dplyr::select(c("ID","Description", "geneID"))})
kegg <- lapply(enrichKEGG_sig, function(x) {x %>% dplyr::select(c("ID","Description", "geneID"))})
react <- lapply(reactome_sig, function(x) {x %>% rownames_to_column("ID") %>% dplyr::select(c("ID","Description", "geneID"))})

lookup <- tibble(gene_name = lm_all[[1]]$gene, gene_name_CAP = str_to_upper(lm_all[[1]]$gene))
replacement_vector <- setNames(lookup$gene_name, lookup$gene_name_CAP)

ipa <- lapply(ipaPathway_sig, function(x) {
  res <- x %>% dplyr::select(c("name","molecules")) %>% dplyr::mutate(ID = name, .before = name)
  colnames(res) <- c("ID", "Description", "geneID")
  res$geneID <- map_chr(res$geneID, ~ str_replace_all(., replacement_vector))
  res$geneID <- str_replace_all(res$geneID, ",", "/")
  return(res)
  })



all_ora_DTvPBS <- rbind(go[[1]],kegg[[1]], react[[1]], ipa[[1]])
all_ora_TregvDT <- rbind(go[[3]],kegg[[3]], react[[3]], ipa[[3]])


library(ComplexHeatmap)
ora_id <- c("GO:0140507", "GO:0042267", "GO:0001910", "GO:0046703", "GO:0001913","GO:0019835","mmu04612","R-MMU-1236974","Interferon gamma signaling","Interferon alpha/beta signaling", "Neutrophil degranulation")
all_ora_DTvPBS[all_ora_DTvPBS$ID %in% ora_id,2]

generateMat <- function(data,index){
  
  res <- data[data$ID %in% ora_id,]
  # res_DTvPBS[res_DTvPBS$ID == "mmu04650", 2] <- "KEGG: Natural killer cell mediated cytotoxicity"
  pathways <- res[["Description"]]
  
  genes <- sort(unique(unlist(strsplit(res[["geneID"]], "/"))))
  
  mat <- matrix(0, nrow = length(pathways), ncol = length(genes))
  rownames(mat) <- pathways
  colnames(mat) <- genes
  
  for (i in seq_along(pathways)) {
    gns <- sort(unique(unlist(strsplit(res[i, "geneID"], "/"))))
    print(gns)
    mat[i, which(colnames(mat) %in% gns)] <- lm_sig[[index]][ gns, "logFC"]
  }
  
  rownames(mat) <- rownames(mat) %>% str_wrap(35)
  return(mat)
}

mat1 <- generateMat(all_ora_DTvPBS, 1) %>% as.data.frame()
mat2 <- generateMat(all_ora_TregvDT,3) %>% as.data.frame()

mat1[setdiff(names(mat2), names(mat1))] <- 0
mat2[setdiff(names(mat1), names(mat2))] <- 0

mat <- rbind(mat1,mat2)

library(RColorBrewer)

anno_col <-  brewer.pal(4,"Set1")%>% setNames(c("GO", "KEGG", "Reactome", "IPA"))
anno_col_2 <-  compColour %>% setNames(Comp)
library(ggplotify)

createHeat <- function(matrix, compIndex, col, legend){
  anno <- data.frame("Database" = c(rep("GO",6), rep("KEGG", 1), "Reactome",rep("IPA", 3)),
                   "Constrast" = rep(Comp[compIndex], 11))
  breaks <-seq(-4,4, by = 1)
  # anno <- data.frame("Database" = c(rep("GO",6), rep("KEGG", 1), "Reactome", rep("GO",6), rep("KEGG", 1), "Reactome"),
  #                    "Constrast" = c(rep("DT vs PBS", 8), rep("Treg vs DT", 8)))
  p <- ComplexHeatmap::pheatmap(
    # MAIN
    mat = matrix,
    color = colorRampPalette(rev(c("#FB8072","#FDB462","grey98","#3b9888","#346f97")))(length(breaks)),
    scale = "none",
    
    # Col
    cluster_cols = F,
    # gaps_col = c(6,11),
    # cutree_cols = 2,
    border_color = "grey90",
    angle_col = "90",
    # treeheight_col = 20,
    
    # Row
    cluster_rows = F,
    # cutree_rows = 2,
    # treeheight_row = 30,
    # clustering_distance_rows = "euclidean",
    labels_col = as.expression(lapply(colnames(matrix), function(a) bquote(italic(.(a))))),
    
    # Labs
    # main = paste0(pathName, "\n"),
    show_colnames = col,
    legend = legend,
    breaks = breaks,
    heatmap_legend_param = list(title = "LogFC",
                                direction= "horizontal",
                                merge_legend = T,
                                legend_direction = "horizontal",
                                legend_width = unit(4, "cm")),
    # heatmap_legend_param = list(title = "LogFC", legend_width = unit(3, "cm"), limit = c(-4,4)),
    
    # Annotation
    annotation_legend = legend,
    # legend_labels = T,
    annotation_row = anno,
    annotation_colors = list("Database" = anno_col, "Constrast" = anno_col_2),
    annotation_names_row = col,
    
    # Fonts
    fontfamily = "Arial Narrow",
    fontsize = 11,
    fontsize_col = 9,
    fontsize_number = 11,
    fontsize_row = 10,
    row_names_side = "left", row_dend_side = "right"
    
  ) %>% as.ggplot()

  # if (savePlots == T) {
  #   png(filename = here::here(paste0("2_plots/functionalHeat_",Comp[compIndex],".svg")),width = 7.5,height = 3)
  #   draw(p, merge_legend = T, heatmap_legend_side = "right", 
  #        annotation_legend_side = "right")
  #   dev.off()
  # }
  # 
  # draw(p, merge_legend = T, heatmap_legend_side = "right",
  #      annotation_legend_side = "right")
  # 
  
}

mat1 <- mat1 %>% as.data.frame() %>%  dplyr::select(starts_with(LETTERS))
mat2 <- mat2 %>% as.data.frame() %>%  dplyr::select(starts_with(LETTERS))

p1 <- createHeat(mat1 %>% as.matrix(), 1, col = F,legend = T)
p2 <- createHeat(mat2 %>% as.matrix(), 3, col = T,legend = T)

# draw(p, merge_legend = T, heatmap_legend_side = "right", 
#        annotation_legend_side = "right")

# p3 <- createHeat(mat %>% as.matrix(),)
sampleHeatmap <- p1/ p2
sampleHeatmap
png(filename = here::here(paste0("2_plots/functionalHeat.png")),width = 23,height = 18, res = 900, units = "cm")
sampleHeatmap
dev.off()

sampleHeatmap
# ggsave(filename = "sampleHeat.svg",plot = sampleHeatmap,path = here::here("2_plots/"),width = 25.5,height = 20,units = "cm")

```




```{r}
combine_kegg+combine_react

combine_kegg_react <- wrap_plots(list(combine_kegg, combine_react)) + 
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A") & 
  bossTheme(base_size = 12, legend = "none") &
  theme(legend.box.margin = margin(-5, 0, 0, -50, unit = "mm"),
        plot.tag.position = "topleft",
        plot.tag = element_text(family = "Arial", face='plain', size = 18),
        # plot.margin = margin(1, 1, 1, 0, unit = "pt"),
        axis.text.y = element_text(family = "Arial Narrow", face = "plain", size = 10, hjust = 1),
        axis.text.x = element_text(family =  "Arial", face = "plain", size = 11, hjust = 1, vjust = 1, angle = 40))

ggsave(filename = "combine_kegg_react_dotplot.png", plot = combine_kegg_react, path = here::here("2_plots/3_FA/"),
           width = 21, height = 27, units = "cm")

combine_kegg_react

```

```{r}
library(patchwork)
library(figpatch)
images <- list(pca = fig(here::here("2_plots/1_QC/3d_pca.png"),aspect.ratio = "free"),
               venn = fig(here::here("2_plots/2_DE/venn_2comp.png"),aspect.ratio = "free"),
               hmap = fig(here::here("2_plots/functionalHeat_manualAdj.png"),aspect.ratio = "free"))


design = "
AABB
CCCC
CCCC
"

fig <- images[[1]] + images[[2]] + images[[3]] +
  plot_layout(design = design, heights = c(2.5,3.5,3.5)) +
  plot_annotation(tag_levels = "A") & 
  theme(plot.tag.position = "topleft",
        plot.tag = element_text(family = "Arial Narrow", face='bold', size = 16),
        # plot.margin = margin(4,5,4,5),
        # legend.position = "bottom",
        # legend.background = element_rect(color = NA),
        # legend.title = element_blank()
        )

ggsave(filename = "figure.png", plot = fig, path = here::here("2_plots/"), width = 23, height = 27, units = "cm",dpi = 900)
```

