---
title: "Paternal beta-defensin 22 promotes fertility and fecundity through effects on maternal immune tolerance and receptivity to implantation in mice"
site: workflowr::wflow_site
---
### Ricky A. Matias^1^, Hon Yeung Chan^1^, Ha M. Tran^1^, John E. Schjenken^1,2,3^, Peck Y. Chin^1^, David J. Sharkey^1^, Lachlan M. Moldenhauer^1^, and Sarah A. Robertson^1\*^

**Keywords: Beta-defensin, uterus, embryo implantation, immune tolerance**

**Author affiliations:**

^1^ The Robinson Research Institute and Adelaide Medical School, University of Adelaide, Adelaide, SA 5000, Australia.
^2^ Hunter Medical Research Institute, Infertility and Reproduction Research Program, New Lambton Heights, NSW 2305, Australia.
^3^ Priority Research Centre for Reproductive Science, School of Environmental and Life Sciences, Discipline of Biological Sciences, The University of Newcastle, University Drive, Callaghan, NSW 2308, Australia

^\*^ **Corresponding author:** Sarah A. Robertson, The Robinson Research Institute, Adelaide Medical School, University of Adelaide, Adelaide, SA 5005, Australia. 

E-mail: sarah.robertson@adelaide.edu.au

**Conflict of Interest Statement:** The authors have declared that no conflict of interest exists

# Abstract

Molecular agents in seminal plasma and sperm interact with the female reproductive tract at coitus to promote an immune response that promotes female receptivity for pregnancy. This study investigates the physiological significance of DEFB22, the murine orthologue of human DEFB126, in mediating effects of seminal fluid on fertility and fecundity. Using mice with a null mutation in Defb22 (Defb22-/- mice) generated by CRISPR technology, we showed wild-type females mated to Defb22-/- males had poorer reproductive outcomes than females mated to wild-type Defb22+/+ littermates, with reduced implantation rates, increased post-implantation fetal loss, and fetal growth restriction in late gestation. RNAseq analysis of the uterine endometrium just prior to embryo implantation showed altered expression of several genes associated with immune-regulatory and tissue remodelling pathways involved in implantation when females were mated with Defb22-/- males. Upstream regulator analysis implicated impaired signaling through TLR4, IL6, and TNF when DEFB22 was absent. Flow cytometry analysis on uterine draining lymph nodes in the peri-implantation phase demonstrated that compared to Defb22+/+ males, Defb22-/- males elicited a smaller expansion of regulatory T cells (Treg cells) in uterine draining lymph nodes. These data demonstrate that male DEFB22 is required for optimal seminal fluid regulation of a permissive female immune response after coitus, in order to underpin implantation receptivity and successful pregnancy outcome.